package propiedades.gui;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import propiedades.negocio.ArriendoPropiedad;
import propiedades.negocio.ListaPropiedad;
import propiedades.negocio.Propiedad;
import propiedades.negocio.VentaPropiedad;

/**
 *
 * @author MisaoDev <https://github.com/MisaoDev>
 */
public class VentanaPrincipal extends javax.swing.JFrame {
  
  private static final int TIPO_ARRIENDO = 1;
  private static final int TIPO_VENTA = 2;
  private static DocumentListener listenerTextoValor;
  
  private ListaPropiedad datos;
  
  /**
   * Creates new form VentanaPrincipal
   * @param datos
   */
  public VentanaPrincipal(ListaPropiedad datos) {
    this.datos = datos;
    initComponents();
    
    listenerTextoValor = new DocumentListener() {
      @Override
      public void insertUpdate(DocumentEvent e) {
        updateFieldState();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        updateFieldState();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        updateFieldState();
      }

      protected void updateFieldState() {
        try {
          int valorUF = Integer.parseInt(txtValor.getText());
          long pesos = (long) (valorUF * VentaPropiedad.VALOR_UF);
          txtConversión.setText(Long.toString(pesos));
          
        } catch (NumberFormatException e) {
          txtConversión.setText("N/A");
        }
      }
    };
    
    txtValor.getDocument().addDocumentListener(listenerTextoValor);
    txtConversión.setVisible(false);
    labConversión.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnGroupTipo = new javax.swing.ButtonGroup();
    jTabs = new javax.swing.JTabbedPane();
    jpArriendos = new javax.swing.JPanel();
    jScrollPane4 = new javax.swing.JScrollPane();
    tableArriendo = new javax.swing.JTable();
    btnBorrarArriendo = new javax.swing.JButton();
    jpVentas = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableVenta = new javax.swing.JTable();
    btnBorrarVenta = new javax.swing.JButton();
    jpAgregar = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    txtComuna = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtDormitorios = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtBaños = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    txtMetros = new javax.swing.JTextField();
    labValor = new javax.swing.JLabel();
    txtValor = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    radioArriendo = new javax.swing.JRadioButton();
    radioVenta = new javax.swing.JRadioButton();
    jButton3 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    txtConversión = new javax.swing.JTextField();
    labConversión = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(600, 440));
    setPreferredSize(new java.awt.Dimension(600, 500));

    jTabs.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jTabsStateChanged(evt);
      }
    });

    tableArriendo.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "#", "Comuna", "Dormitorios", "Baños", "Metros²", "Valor en pesos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tableArriendo.getTableHeader().setReorderingAllowed(false);
    jScrollPane4.setViewportView(tableArriendo);
    tableArriendo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    if (tableArriendo.getColumnModel().getColumnCount() > 0) {
      tableArriendo.getColumnModel().getColumn(0).setMinWidth(22);
      tableArriendo.getColumnModel().getColumn(0).setPreferredWidth(22);
      tableArriendo.getColumnModel().getColumn(0).setMaxWidth(22);
      tableArriendo.getColumnModel().getColumn(1).setResizable(false);
      tableArriendo.getColumnModel().getColumn(2).setPreferredWidth(80);
      tableArriendo.getColumnModel().getColumn(3).setMinWidth(80);
      tableArriendo.getColumnModel().getColumn(3).setPreferredWidth(80);
      tableArriendo.getColumnModel().getColumn(3).setMaxWidth(80);
      tableArriendo.getColumnModel().getColumn(4).setMinWidth(80);
      tableArriendo.getColumnModel().getColumn(4).setPreferredWidth(80);
      tableArriendo.getColumnModel().getColumn(5).setMinWidth(60);
    }

    btnBorrarArriendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/trash-solid-36.png"))); // NOI18N
    btnBorrarArriendo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBorrarArriendoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jpArriendosLayout = new javax.swing.GroupLayout(jpArriendos);
    jpArriendos.setLayout(jpArriendosLayout);
    jpArriendosLayout.setHorizontalGroup(
      jpArriendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpArriendosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jpArriendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
          .addComponent(btnBorrarArriendo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    jpArriendosLayout.setVerticalGroup(
      jpArriendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpArriendosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnBorrarArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabs.addTab("Arriendos", new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/table-regular-36-b.png")), jpArriendos); // NOI18N

    tableVenta.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "#", "Comuna", "Dormitorios", "Baños", "Metros²", "Valor en UF", "Valor en pesos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tableVenta.getTableHeader().setReorderingAllowed(false);
    jScrollPane2.setViewportView(tableVenta);
    tableVenta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    if (tableVenta.getColumnModel().getColumnCount() > 0) {
      tableVenta.getColumnModel().getColumn(0).setMinWidth(22);
      tableVenta.getColumnModel().getColumn(0).setPreferredWidth(22);
      tableVenta.getColumnModel().getColumn(0).setMaxWidth(22);
      tableVenta.getColumnModel().getColumn(1).setResizable(false);
      tableVenta.getColumnModel().getColumn(2).setPreferredWidth(80);
      tableVenta.getColumnModel().getColumn(3).setMinWidth(80);
      tableVenta.getColumnModel().getColumn(3).setPreferredWidth(80);
      tableVenta.getColumnModel().getColumn(3).setMaxWidth(80);
      tableVenta.getColumnModel().getColumn(4).setMinWidth(80);
      tableVenta.getColumnModel().getColumn(4).setPreferredWidth(80);
      tableVenta.getColumnModel().getColumn(4).setMaxWidth(80);
      tableVenta.getColumnModel().getColumn(5).setMinWidth(60);
      tableVenta.getColumnModel().getColumn(6).setMinWidth(120);
    }

    btnBorrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/trash-solid-36.png"))); // NOI18N
    btnBorrarVenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBorrarVentaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jpVentasLayout = new javax.swing.GroupLayout(jpVentas);
    jpVentas.setLayout(jpVentasLayout);
    jpVentasLayout.setHorizontalGroup(
      jpVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpVentasLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jpVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
          .addComponent(btnBorrarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    jpVentasLayout.setVerticalGroup(
      jpVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVentasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnBorrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabs.addTab("Ventas", new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/table-regular-36.png")), jpVentas); // NOI18N

    jLabel5.setText("Comuna");

    jLabel6.setText("N° dormitorios");

    jLabel7.setText("N° baños");

    jLabel8.setText("Metros cuadrados");

    labValor.setText("Valor en pesos");

    txtValor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtValorActionPerformed(evt);
      }
    });

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

    btnGroupTipo.add(radioArriendo);
    radioArriendo.setSelected(true);
    radioArriendo.setText("Arriendo de propiedad");
    radioArriendo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radioArriendoActionPerformed(evt);
      }
    });

    btnGroupTipo.add(radioVenta);
    radioVenta.setText("Venta de propiedad");
    radioVenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radioVentaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(radioArriendo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(radioVenta)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioArriendo)
          .addComponent(radioVenta))
        .addContainerGap(21, Short.MAX_VALUE))
    );

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/save-solid-36.png"))); // NOI18N
    jButton3.setText("Guardar");
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/file-blank-regular-36.png"))); // NOI18N
    jButton5.setText("Limpiar campos");
    jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    txtConversión.setEditable(false);

    labConversión.setText("pesos");

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/dice-6-regular-36.png"))); // NOI18N
    jButton6.setText("Datos aleatorios");
    jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labValor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtComuna)
              .addComponent(txtDormitorios, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
              .addComponent(txtBaños, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
              .addComponent(txtMetros, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
              .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtConversión, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labConversión, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(txtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(txtDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(txtBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labValor)
          .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labConversión)
          .addComponent(txtConversión, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(23, 23, 23))
    );

    javax.swing.GroupLayout jpAgregarLayout = new javax.swing.GroupLayout(jpAgregar);
    jpAgregar.setLayout(jpAgregarLayout);
    jpAgregarLayout.setHorizontalGroup(
      jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpAgregarLayout.createSequentialGroup()
        .addContainerGap(65, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(65, Short.MAX_VALUE))
    );
    jpAgregarLayout.setVerticalGroup(
      jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpAgregarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabs.addTab("Agregar propiedad", new javax.swing.ImageIcon(getClass().getResource("/propiedades/gui/message-square-add-solid-36-g.png")), jpAgregar); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabs)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabs)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void radioArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioArriendoActionPerformed
    cambioTipoPropiedad(TIPO_ARRIENDO);
  }//GEN-LAST:event_radioArriendoActionPerformed

  private void radioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVentaActionPerformed
    cambioTipoPropiedad(TIPO_VENTA);
  }//GEN-LAST:event_radioVentaActionPerformed

  private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed

  }//GEN-LAST:event_txtValorActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    txtComuna.setText("");
    txtDormitorios.setText("");
    txtBaños.setText("");
    txtMetros.setText("");
    txtValor.setText("");
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String comuna = txtComuna.getText();
    int dormitorios = 0, baños = 0, metros = 0, valor = 0;
    
    try {
      dormitorios = Integer.parseInt(txtDormitorios.getText());
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Debe ingresar un número de dormitorios válido."); return;
    }
    
    try {
      baños = Integer.parseInt(txtBaños.getText());
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Debe ingresar un número de baños válido."); return;
    }
    
    try {
      metros = Integer.parseInt(txtMetros.getText());
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Debe ingresar un número de metros cuadrados válido."); return;
    }
    
    try {
      valor = Integer.parseInt(txtValor.getText());
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Debe ingresar un precio válido."); return;
    }
    
    try {
      Propiedad p = radioArriendo.isSelected() ?
             new ArriendoPropiedad(valor, dormitorios, baños, metros, comuna) :
             new VentaPropiedad(valor, dormitorios, baños, metros, comuna);
      datos.add(p);
    } catch (IllegalArgumentException e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabsStateChanged
    DefaultTableModel model; int i;
    
    switch (jTabs.getSelectedIndex()) {
      case 0:
        actualizarTableArriendo();
        break;
        
      case 1:
        actualizarTableVenta();
        break;
        
      default:
        break;
    }
  }//GEN-LAST:event_jTabsStateChanged
  
  private void actualizarTableArriendo() {
    DefaultTableModel model = (DefaultTableModel) tableArriendo.getModel();
    model.setRowCount(0);
    
    int i = 0;
    for (Propiedad p : datos.getPropiedades()) {
      if (p instanceof ArriendoPropiedad) {

        Object[] row = new Object[6];
        row[0] = i;
        row[1] = p.getComuna();
        row[2] = p.getNúmeroDormitorios();
        row[3] = p.getNúmeroBaños();
        row[4] = p.getMetrosCuadrados();
        int valor = ((ArriendoPropiedad) p).getValorArriendo();
        row[5] = String.format("$ %,d", valor);
        model.addRow(row);

      }
      i++;
    }
  }
  
  private void actualizarTableVenta() {
    DefaultTableModel model = (DefaultTableModel) tableVenta.getModel();
    model.setRowCount(0);
    
    int i = 0;
    for (Propiedad p : datos.getPropiedades()) {
      if (p instanceof VentaPropiedad) {

        Object[] row = new Object[7];
        row[0] = i;
        row[1] = p.getComuna();
        row[2] = p.getNúmeroDormitorios();
        row[3] = p.getNúmeroBaños();
        row[4] = p.getMetrosCuadrados();
        int valor = ((VentaPropiedad) p).getPrecioVentaUF();
        row[5] = String.format("UF$ %,d", valor);
        long pesos = ((VentaPropiedad) p).getPrecioVentaPesos();
        row[6] = String.format("$ %,d", pesos);
        model.addRow(row);

      }
      i++;
    }
  }
  
  private void btnBorrarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarArriendoActionPerformed
    int[] selectedRows = tableArriendo.getSelectedRows();
    if (selectedRows.length == 0) {
      JOptionPane.showMessageDialog(this, "Debe seleccionar una o más propiedades para eliminar.");
      return;
    }
    
    DefaultTableModel model = (DefaultTableModel) tableArriendo.getModel();
    
    for (int i = selectedRows.length - 1; i >= 0; i--) {
      int row = selectedRows[i];
      int índiceDatos = (int) model.getValueAt(row, 0);
      datos.remove(índiceDatos);
      model.removeRow(row);
    }
    
    actualizarTableArriendo();
  }//GEN-LAST:event_btnBorrarArriendoActionPerformed

  private static final String[] LISTA_COMUNAS = {"ANTOFAGASTA", "CALAMA", "VALPARAÍSO", "VIÑA DEL MAR", "LOS ANDES",
    "SAN FELIPE", "SANTIAGO", "PROVIDENCIA", "LAS CONDES", "INDEPENDENCIA", "SAN JOAQUÍN", "SAPOLANDIA"};
  
  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Random random = new Random();
    String comuna; int dormitorios, baños, metros, valor;
    
    comuna = LISTA_COMUNAS[random.nextInt(LISTA_COMUNAS.length)];
    dormitorios = random.nextInt(9) + 1;
    baños = random.nextInt(4) + 1;
    metros = random.nextInt(201) + 100;
    valor = radioArriendo.isSelected() ?
            (random.nextInt(401) + 100) * 1000:
            random.nextInt(4001) + 1000;
            
    txtComuna.setText(comuna);
    txtDormitorios.setText(Integer.toString(dormitorios));
    txtBaños.setText(Integer.toString(baños));
    txtMetros.setText(Integer.toString(metros));
    txtValor.setText(Integer.toString(valor));
    
  }//GEN-LAST:event_jButton6ActionPerformed

  private void btnBorrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVentaActionPerformed
    int[] selectedRows = tableVenta.getSelectedRows();
    if (selectedRows.length == 0) {
      JOptionPane.showMessageDialog(this, "Debe seleccionar una o más propiedades para eliminar.");
      return;
    }
    
    DefaultTableModel model = (DefaultTableModel) tableVenta.getModel();
    
    for (int i = selectedRows.length - 1; i >= 0; i--) {
      int row = selectedRows[i];
      int índiceDatos = (int) model.getValueAt(row, 0);
      datos.remove(índiceDatos);
      model.removeRow(row);
    }
    
    actualizarTableVenta();
  }//GEN-LAST:event_btnBorrarVentaActionPerformed

  private void cambioTipoPropiedad(int tipo) {
    if (tipo == TIPO_ARRIENDO) {
      labValor.setText("Valor en pesos");
      txtConversión.setVisible(false);
      labConversión.setVisible(false);
    } else {
      labValor.setText("Valor en UF");
      txtConversión.setVisible(true);
      labConversión.setVisible(true);
    }
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        //new VentanaPrincipal().setVisible(true);
      }
    });
  }

  public void setDatos(ListaPropiedad datos) {
    this.datos = datos;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBorrarArriendo;
  private javax.swing.JButton btnBorrarVenta;
  private javax.swing.ButtonGroup btnGroupTipo;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTabbedPane jTabs;
  private javax.swing.JPanel jpAgregar;
  private javax.swing.JPanel jpArriendos;
  private javax.swing.JPanel jpVentas;
  private javax.swing.JLabel labConversión;
  private javax.swing.JLabel labValor;
  private javax.swing.JRadioButton radioArriendo;
  private javax.swing.JRadioButton radioVenta;
  private javax.swing.JTable tableArriendo;
  private javax.swing.JTable tableVenta;
  private javax.swing.JTextField txtBaños;
  private javax.swing.JTextField txtComuna;
  private javax.swing.JTextField txtConversión;
  private javax.swing.JTextField txtDormitorios;
  private javax.swing.JTextField txtMetros;
  private javax.swing.JTextField txtValor;
  // End of variables declaration//GEN-END:variables
}
