package sapo.saposlagartos.gui;

import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import sapo.saposlagartos.DaoPlayer;
import sapo.saposlagartos.Main;

/**
 *
 * @author MisaoDev <https://github.com/MisaoDev>
 */
public class LoginForm extends javax.swing.JFrame {
  
  private static final String USERNAME_PATTERN = "^[a-zA-Z]([a-zA-Z0-9]){3,28}[a-zA-Z0-9]$";
  
  /**
   * Creates new form LoginForm
   */
  public LoginForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelBanner = new javax.swing.JLabel();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
    jpCards = new javax.swing.JPanel();
    jpLogin = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    textLoginName = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    btnRegisterForm = new javax.swing.JButton();
    textLoginPass = new javax.swing.JPasswordField();
    jpRegister = new javax.swing.JPanel();
    btnRegisterSend = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    textRegisterName = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    textRegisterEmail = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    textRegisterPass1 = new javax.swing.JPasswordField();
    textRegisterPass2 = new javax.swing.JPasswordField();
    btnReturn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Sapos y Lagartos - Iniciar sesión");
    setResizable(false);

    jLabelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapo/saposlagartos/assets/login.png"))); // NOI18N

    jpCards.setLayout(new java.awt.CardLayout());

    jLabel3.setText("Usuario");

    jLabel4.setText("Contraseña");

    btnLogin.setText("Iniciar sesión");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    btnRegisterForm.setText("Crear una cuenta");
    btnRegisterForm.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegisterFormActionPerformed(evt);
      }
    });

    textLoginPass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textLoginPassActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
    jpLogin.setLayout(jpLoginLayout);
    jpLoginLayout.setHorizontalGroup(
      jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpLoginLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textLoginName)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jpLoginLayout.createSequentialGroup()
            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
            .addComponent(btnRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(textLoginPass))
        .addContainerGap())
    );
    jpLoginLayout.setVerticalGroup(
      jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpLoginLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addGap(1, 1, 1)
        .addComponent(textLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel4)
        .addGap(1, 1, 1)
        .addComponent(textLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
          .addComponent(btnRegisterForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    jpCards.add(jpLogin, "cardLogin");

    btnRegisterSend.setText("Registrarse");
    btnRegisterSend.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegisterSendActionPerformed(evt);
      }
    });

    jLabel1.setText("Nombre de usuario");

    textRegisterName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textRegisterNameActionPerformed(evt);
      }
    });

    jLabel2.setText("Correo electrónico");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textRegisterName)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2))
            .addGap(0, 173, Short.MAX_VALUE))
          .addComponent(textRegisterEmail))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(1, 1, 1)
        .addComponent(textRegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel2)
        .addGap(1, 1, 1)
        .addComponent(textRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel7.setText("Contraseña");

    jLabel8.setText("Confirmar contraseña");

    textRegisterPass1.setText("password");
    textRegisterPass1.setSelectionEnd(0);
    textRegisterPass1.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        textRegisterPass1FocusGained(evt);
      }
    });

    textRegisterPass2.setText("pazzword");
    textRegisterPass2.setSelectionEnd(0);
    textRegisterPass2.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        textRegisterPass2FocusGained(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel7)
              .addComponent(jLabel8))
            .addGap(0, 154, Short.MAX_VALUE))
          .addComponent(textRegisterPass2)
          .addComponent(textRegisterPass1))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel7)
        .addGap(1, 1, 1)
        .addComponent(textRegisterPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel8)
        .addGap(1, 1, 1)
        .addComponent(textRegisterPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapo/saposlagartos/assets/ico-return.png"))); // NOI18N
    btnReturn.setIconTextGap(0);
    btnReturn.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btnReturn.setMaximumSize(new java.awt.Dimension(38, 38));
    btnReturn.setMinimumSize(new java.awt.Dimension(38, 38));
    btnReturn.setPreferredSize(new java.awt.Dimension(38, 38));
    btnReturn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnReturnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jpRegisterLayout = new javax.swing.GroupLayout(jpRegister);
    jpRegister.setLayout(jpRegisterLayout);
    jpRegisterLayout.setHorizontalGroup(
      jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpRegisterLayout.createSequentialGroup()
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jpRegisterLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnRegisterSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jpRegisterLayout.setVerticalGroup(
      jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpRegisterLayout.createSequentialGroup()
        .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
          .addComponent(btnRegisterSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    jpCards.add(jpRegister, "cardRegister");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jLabelBanner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(filler1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jpCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabelBanner)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jpCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void textLoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginPassActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textLoginPassActionPerformed

  private void textRegisterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegisterNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textRegisterNameActionPerformed

  private void btnRegisterFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterFormActionPerformed
    CardLayout card = (CardLayout)jpCards.getLayout();
    card.show(jpCards, "cardRegister");
    textRegisterName.requestFocus();
  }//GEN-LAST:event_btnRegisterFormActionPerformed

  private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
    CardLayout card = (CardLayout)jpCards.getLayout();
    card.show(jpCards, "cardLogin");
  }//GEN-LAST:event_btnReturnActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    if (textLoginName.getText().isEmpty()) {
      textLoginName.requestFocus(); return;
    } else if (textLoginPass.getPassword().length == 0) {
      textLoginPass.requestFocus(); return;
    }
    
    String name = textLoginName.getText();
    String enteredPassword = new String(textLoginPass.getPassword());
    
    DaoPlayer dao = new DaoPlayer();
    int passCheck = dao.checkPassword(name, enteredPassword);
    
    switch (passCheck) {
      case 1:
        JOptionPane.showMessageDialog(this, "Hola sapo :)");
        ControlPanel gui = new ControlPanel();
        gui.setLocationRelativeTo(null);
        gui.setVisible(true);
        gui.init(name);
        this.setVisible(false);
        break;
      case 0:
        JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
        break;
      default:
        JOptionPane.showMessageDialog(this, "El usuario no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        break;
    }
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnRegisterSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSendActionPerformed
    String name = textRegisterName.getText();
    String email = textRegisterEmail.getText();
    String pass1 = new String(textRegisterPass1.getPassword());
    String pass2 = new String(textRegisterPass2.getPassword());
    String password = pass1.equals(pass2) ? pass1 : "";
    
    if (name.isEmpty()) {
      textRegisterName.requestFocus(); return;
    } else if (email.isEmpty()) {
      textRegisterEmail.requestFocus(); return;
    } else if (pass1.isEmpty()) {
      textRegisterPass1.requestFocus(); return;
    } else if (pass2.isEmpty() || password.isEmpty()) {
      textRegisterPass2.requestFocus(); return;
    }
    
    Pattern p = Pattern.compile(USERNAME_PATTERN);
    Matcher m = p.matcher(name);
    if (! m.matches()) {
      JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y números y debe comenzar por una letra.");
      return;
    }
    
    DaoPlayer dao = new DaoPlayer();
    if (dao.exists(name)) {
      JOptionPane.showMessageDialog(this, "El usuario ya existe.");
      return;
    }
    dao.insert(name, email, password);
    JOptionPane.showMessageDialog(this, "Usuario creado con éxito (creo).");
    
    CardLayout card = (CardLayout)jpCards.getLayout();
    card.show(jpCards, "cardLogin");
  }//GEN-LAST:event_btnRegisterSendActionPerformed

  private void textRegisterPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRegisterPass1FocusGained
    textRegisterPass1.selectAll();
  }//GEN-LAST:event_textRegisterPass1FocusGained

  private void textRegisterPass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRegisterPass2FocusGained
    textRegisterPass2.selectAll();
  }//GEN-LAST:event_textRegisterPass2FocusGained

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLogin;
  private javax.swing.JButton btnRegisterForm;
  private javax.swing.JButton btnRegisterSend;
  private javax.swing.JButton btnReturn;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabelBanner;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jpCards;
  private javax.swing.JPanel jpLogin;
  private javax.swing.JPanel jpRegister;
  private javax.swing.JTextField textLoginName;
  private javax.swing.JPasswordField textLoginPass;
  private javax.swing.JTextField textRegisterEmail;
  private javax.swing.JTextField textRegisterName;
  private javax.swing.JPasswordField textRegisterPass1;
  private javax.swing.JPasswordField textRegisterPass2;
  // End of variables declaration//GEN-END:variables
}
